WITH 
    CTE AS (
        SELECT ORD.PRODUCT_ID, SUM(ORD.AMOUNT) AS AMOUNT
        FROM FOOD_ORDER ORD
        WHERE YEAR(ORD.PRODUCE_DATE) = 2022 
            AND MONTH(ORD.PRODUCE_DATE) = 5
        GROUP BY ORD.PRODUCT_ID
    )
# -- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, (CTE.AMOUNT * PRO.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO
    JOIN CTE ON PRO.PRODUCT_ID = CTE.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC