
# 프론트 엔드 카테고리의 name들을 가져옴
WITH
    CTE AS (
        SELECT NAME, CODE
        FROM SKILLCODES
        WHERE CATEGORY = 'Front End'
    )

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN CTE
WHERE (D.SKILL_CODE & CTE.CODE) <> 0
ORDER BY D.ID ASC
