WITH UNAVAILABLE AS (
    SELECT DISTINCT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING(CAR_ID)
    WHERE
        CAR_TYPE IN ('세단', 'SUV')
        AND START_DATE <= DATE('2022-11-30') AND END_DATE >= DATE('2022-11-01')
)
SELECT *
FROM (
    SELECT
        CAR_ID
        , C.CAR_TYPE
        , ROUND(DAILY_FEE * 30 * (100.0 - IFNULL(DISCOUNT_RATE, 0)) / 100) 'FEE'
    FROM
        CAR_RENTAL_COMPANY_CAR C
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE 
        C.CAR_TYPE IN ('세단', 'SUV')
        AND D.DURATION_TYPE = '30일 이상'
        AND CAR_ID NOT IN (SELECT CAR_ID FROM UNAVAILABLE)
    ORDER BY
        3 DESC, 2 ASC, 1 DESC
) T
WHERE FEE >= 500000 AND FEE < 2000000
;