WITH
 CTE AS (
    SELECT 
        INFO.FISH_TYPE, COUNT(*) AS COUNT, AVG(IFNULL(LENGTH, 10)) AS AVG, MAX(LENGTH) AS MAX_LENGTH
    FROM 
        FISH_INFO INFO
    GROUP BY 
        FISH_TYPE
 )
 
SELECT 
     COUNT AS FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM
    CTE
WHERE AVG >= 33
ORDER BY 
    FISH_TYPE ASC